title: Derby-Training
paginate: 5
theme: hugo-PaperMod
baseURL: https://www.derby-training.com
params:
  description: 'A simple site to share roller derby exercices with the community'
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    title: derby-training
    imageUrb: 'derby-training.com'
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Bonjour  \U0001F44B ðŸ›¼"
    Content: Fan de roller derby ? Envie de t'entrainer ? Tu es sur le bon site, j'espÃ¨re que tu trouveras des exercices Ã  ton gout !
      Tu trouveras Ã©galement un outil permettant de visualiser un track en direct. Va voir la section Jamboard. J'ai Ã©gallement crÃ©er un petit lexique histoire de m'y retrouver dans le langage technique du roller derby.

menu:
  main:
    - name: Tags
      url: /tags/
      weight: 1 
    - name: Lexique
      url: /lexique
    - name: Regles
      url: /regles
    - name: Proposer
      url: /proposer
    - name: Jamboard
      url: /jamboard.html
taxonomies:
  category: categories
  tag: tags
  series: series

ShowToc: false

  #mediaTypes:
  #  application/x-php:
  #    suffixes:
  #      - php
  #outputFormats:
  #  PHP:
  #    mediaType: application/x-php
  #    isPlainText: true
  #   baseName: index
 
ShowShareButtons: true

enableEmoji: true
